### ISSUE TITLE
Is this ready to be used?

### ISSUE THREAD

**Issue by mogusbi** [brandonroberts/angular-jest-build#1]
Is this ready to be used and if so, are there any instruction to get up and running?

Thought it would be as easy and installing and replacing `"builder": "@angular-devkit/build-angular:karma"` with `"builder": "angular-jest-build"` in my angular.json but sadly i just get `Builder 'angular-jest-build' cannot be resolved`

**Comment by brandonroberts** [comment]
Sort of. You can use it today with a little manual setup. If you do the install steps for the `jest-preset-angular` package, then you can use `angular-jest-build:test` in the builder and remove all the karma options. We are working on automating all of the installation and manual setup.

**Comment by mogusbi** [comment]
That's spot on, thank you very much!

**Comment by delasteve** [comment]
@mogusbi, I'll add this to the README tonight, but for the time being...

Run:
```sh
npm install --save-dev jest angular-jest-build jest-preset-angular
```

In the root of your project folder (under `/src/`), add the following files: `setupJest.ts` and `jestGlobalMocks.ts`

In `setupJest.ts`, add the following:
```ts
import 'jest-preset-angular';
import './jestGlobalMocks'; // browser mocks globally available for every test
```

In `jestGlobalMocks.ts`, add the following: 
```ts
global['CSS'] = null;

const mock = () => {
  let storage = {};
  return {
    getItem: key => key in storage ? storage[key] : null,
    setItem: (key, value) => storage[key] = value || '',
    removeItem: key => delete storage[key],
    clear: () => storage = {},
  };
};

Object.defineProperty(window, 'localStorage', {value: mock()});
Object.defineProperty(window, 'sessionStorage', {value: mock()});
Object.defineProperty(document, 'doctype', {
  value: '<!DOCTYPE html>'
});
Object.defineProperty(window, 'getComputedStyle', {
  value: () => {
    return {
      display: 'none',
      appearance: ['-webkit-appearance']
    };
  }
});
/**
 * ISSUE: https://github.com/angular/material2/issues/7101
 * Workaround for JSDOM missing transform property
 */
Object.defineProperty(document.body.style, 'transform', {
  value: () => {
    return {
      enumerable: true,
      configurable: true,
    };
  },
});
```

In `package.json` add the following:
```json
"jest": {
  "preset": "jest-preset-angular",
  "setupTestFrameworkScriptFile": "<rootDir>/src/setupJest.ts" // modify this according to your file structure
},
```

In `angular.json` change the test node (`projects.YOUR_APP_NAME_HERE.test`) to be
```
"test": {
  "builder": "angular-jest-build:test",
  "options": { }
},

```

Hope that helps!

**Comment by mogusbi** [comment]
@delasteve Thank you 👍 

I've actually got a couple of projects. When I run `ng test project-name` it just returns the Jest help instructions

```
Usage: jest [--config=<pathToConfigFile>] [TestPathPattern]

Options:
......
```

Is there any further configuration needed to make it work? If I run `ng test` without the project name then it does run but it tries to run all of the tests across the project

**Comment by delasteve** [comment]
@mogusbi: it depends on they type of file structure you have. If you're using the new `projects/` layout, you'll need to provide your own config file. It looks like `jest-preset-angular` makes some assumptions where your `tsconfig.spec.json` is location. It defaults to `<rootDir>/src/tsconfig.spec.json`.

Here's a *rough* example of what you'll need to do until it's done automatically (some modifications may be required)

NOTE: replace `PROJECT_NAME` where used with your actual project name as it's not a reserved keyword, unlike `<rootDir>`

- Remove the `jest` property in `package.json`
- Create the following `jest.config.js` in each project you want (`projects/<PROJECT_NAME>/jest.config.js`)

  ```json
  module.exports = {
    "preset": "../../node_modules/jest-preset-angular/jest-preset.json",
    "globals": {
      "ts-jest": {
        "tsConfigFile": "./tsconfig.spec.json"
      },
      "__TRANSFORM_HTML__": true
    },
    "transform": {
      "^.+\\.(ts|js|html)$": "../../node_modules/jest-preset-angular/preprocessor.js"
    },
    "snapshotSerializers": [
      "../../node_modules/jest-preset-angular/AngularSnapshotSerializer.js",
      "../../node_modules/jest-preset-angular/HTMLCommentSerializer.js"
    ],
    "setupTestFrameworkScriptFile": "./setupJest.ts"
  };
  ```
- Modify your `angular.json` file to the following

```json
"test": {
  "builder": "angular-jest-build:test",
  "options": {
    "jestConfig": "projects/<PROJECT_NAME>/jest.config.js"
  }
},
```

We're also planning on putting a `setupJest.ts` and `jestGlobalMocks.ts` file in each project. Those should be the same as in my previous post. You will just need to move/copy them for each project you want to be able to use `ng test`.

Let me know if you have any further issues as the above is basically the strategy I'm going with the `ng add` schematic.

**Comment by delasteve** [comment]
@mogusbi: I made a quick project to test the above assumptions. It works with `ng test`, `ng test test-app`, and `ng test-app2`. `ng test` will use the default project specified in the `angular.json` file (`test-app`).

Here's the link to the repo: https://github.com/delasteve/angular-jest-build-example
and the commit of changes: https://github.com/delasteve/angular-jest-build-example/commit/eedc4d3a078f90f4dd2ca56b2d692d84efeb4d2f

**Comment by delasteve** [comment]
@mogusbi, I'm going to close this issue as resolved. If you have any further questions, please create a new issue.
